export const bathroomsData = [
    {
      id: 1,
      name: "ห้องน้ำ เซ็นทรัลพลาซา เชียงใหม่ แอร์พอร์ต",
      location: "เซ็นทรัลพลาซา เชียงใหม่ แอร์พอร์ต",
      cleanliness: "สะอาด",
      image: "https://example.com/image1.jpg", // แทนที่ด้วย URL รูปภาพที่เหมาะสม
      reviews: [],
      rating: 4.8,
      latitude: 13.7563,
      longitude: 100.5018,
    },
    {
      id: 2,
      name: "ห้องน้ำ ไมยา ไลฟ์สไตล์ ช้อปปิ้งเซ็นเตอร์",
      location: "ไมยา ไลฟ์สไตล์ ช้อปปิ้งเซ็นเตอร์",
      cleanliness: "สะอาด",
      image: "https://example.com/image2.jpg",
      reviews: [],
      rating: 4.5,
    },
    {
      id: 3,
      name: "ห้องน้ำ กาดสวนแก้ว",
      location: "กาดสวนแก้ว",
      cleanliness: "ปานกลาง",
      image: "https://example.com/image3.jpg",
      reviews: [],
      rating: 4.0,
    },
    {
      id: 4,
      name: "ห้องน้ำ โพรเมนาดา รีสอร์ท มอลล์",
      location: "โพรเมนาดา รีสอร์ท มอลล์",
      cleanliness: "สะอาด",
      image: "https://example.com/image4.jpg",
      reviews: [],
      rating: 4.6,
    },
    {
      id: 5,
      name: "ห้องน้ำ เซ็นทรัลเฟสติวัล เชียงใหม่",
      location: "เซ็นทรัลเฟสติวัล เชียงใหม่",
      cleanliness: "สะอาด",
      image: "https://example.com/image5.jpg",
      reviews: [],
      rating: 4.9,
    },
    {
      id: 6,
      name: "ห้องน้ำ วันนิมมาน",
      location: "วันนิมมาน",
      cleanliness: "สะอาด",
      image: "https://example.com/image6.jpg",
      reviews: [],
      rating: 4.3,
    },
    {
      id: 7,
      name: "ห้องน้ำ ตลาดวโรรส",
      location: "ตลาดวโรรส",
      cleanliness: "ปานกลาง",
      image: "https://example.com/image7.jpg",
      reviews: [],
      rating: 3.8,
    },
    {
      id: 8,
      name: "ห้องน้ำ เชียงใหม่ไนท์บาซาร์",
      location: "เชียงใหม่ไนท์บาซาร์",
      cleanliness: "สะอาด",
      image: "https://example.com/image8.jpg",
      reviews: [],
      rating: 4.5,
    },
  
    // ปั๊มน้ำมัน
    {
      id: 9,
      name: "ห้องน้ำ PTT Station มหาวิทยาลัยเชียงใหม่",
      location: "PTT Station สาขา มหาวิทยาลัยเชียงใหม่",
      cleanliness: "สะอาด",
      image: "https://example.com/image9.jpg",
      reviews: [],
      rating: 4.2,
    },
    {
      id: 10,
      name: "ห้องน้ำ PTT Station กองบิน 41",
      location: "PTT Station กองบิน 41",
      cleanliness: "สะอาด",
      image: "https://example.com/image10.jpg",
      reviews: [],
      rating: 4.1,
    },
    // เพิ่มห้องน้ำตามรายการปั๊มน้ำมันอื่น ๆ...
  
    // สวนสาธารณะ
    {
      id: 20,
      name: "ห้องน้ำ สวนบวกหาด",
      location: "สวนบวกหาด (Buak Hard Public Park)",
      cleanliness: "สะอาด",
      image: "https://example.com/image20.jpg",
      reviews: [],
      rating: 4.3,
    },
    {
      id: 21,
      name: "ห้องน้ำ สวน 700 ปี เชียงใหม่",
      location: "สวน 700 ปี เชียงใหม่ (Chiang Mai 700 Years Park)",
      cleanliness: "สะอาด",
      image: "https://example.com/image21.jpg",
      reviews: [],
      rating: 4.5,
    },
    // เพิ่มห้องน้ำตามรายการสวนสาธารณะอื่น ๆ...
  
    // คาเฟ่
    {
      id: 30,
      name: "ห้องน้ำ Akha Ama Coffee",
      location: "Akha Ama Coffee",
      cleanliness: "สะอาด",
      image: "https://example.com/image30.jpg",
      reviews: [],
      rating: 4.7,
    },
    {
      id: 31,
      name: "ห้องน้ำ The Hideout",
      location: "The Hideout",
      cleanliness: "สะอาด",
      image: "https://example.com/image31.jpg",
      reviews: [],
      rating: 4.6,
    },
    // เพิ่มห้องน้ำตามรายการคาเฟ่อื่น ๆ...
  ];